name: arc_raiders_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: any
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^6.0.0
  freezed_annotation: any
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  retrofit: ">=4.0.0 <4.9.0" # Keep below 4.9.0 to exclude DartMappable
  share_plus: ^12.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.0
dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: any
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  retrofit_generator: ^9.0.0 # Use 9.x series which works with Retrofit 4.8.x
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - .env

